#!/usr/bin/env python3
"""Convert PNGs in assets/ to LVGL C arrays.

Output: src/assets_gen.c with one lv_img_dsc_t per PNG (CF_TRUE_COLOR_ALPHA, RGB565 byte-swapped).
Pairs with: src/assets_gen.h (auto-generated declarations).

Run from repo root:  python3 tools/png_to_lvgl.py
"""
import os, sys, struct
from pathlib import Path
from PIL import Image

ROOT = Path(__file__).resolve().parent.parent
ASSETS = ROOT / "assets"
OUT_C = ROOT / "src" / "assets_gen.c"
OUT_H = ROOT / "src" / "assets_gen.h"

def rgb565_swap(r, g, b):
    """Pack to RGB565 then byte-swap (LV_COLOR_16_SWAP=1 expects this order)."""
    v = ((r & 0xF8) << 8) | ((g & 0xFC) << 3) | (b >> 3)
    return ((v & 0xFF) << 8) | (v >> 8)

def safe_name(p: Path) -> str:
    n = p.stem.lower()
    out = ''.join(ch if ch.isalnum() else '_' for ch in n)
    if out and out[0].isdigit():
        out = '_' + out
    return out

def convert_one(png: Path, c_out, h_out):
    name = safe_name(png)
    img = Image.open(png).convert("RGBA")
    w, h = img.size
    px = img.load()

    c_out.write(f"\n// {png.name} ({w}x{h})\n")
    c_out.write(f"static const LV_ATTRIBUTE_LARGE_CONST uint8_t {name}_map[] = {{\n")

    bytes_written = 0
    for y in range(h):
        c_out.write("  ")
        for x in range(w):
            r, g, b, a = px[x, y]
            c = rgb565_swap(r, g, b)
            c_out.write(f"0x{c & 0xFF:02X},0x{c >> 8:02X},0x{a:02X},")
            bytes_written += 3
        c_out.write("\n")
    c_out.write("};\n\n")

    c_out.write(f"const lv_img_dsc_t {name} = {{\n")
    c_out.write("  .header.cf = LV_IMG_CF_TRUE_COLOR_ALPHA,\n")
    c_out.write("  .header.always_zero = 0,\n")
    c_out.write("  .header.reserved = 0,\n")
    c_out.write(f"  .header.w = {w},\n")
    c_out.write(f"  .header.h = {h},\n")
    c_out.write(f"  .data_size = {bytes_written},\n")
    c_out.write(f"  .data = {name}_map,\n")
    c_out.write("};\n")

    h_out.write(f"extern const lv_img_dsc_t {name};\n")
    print(f"  {png.name}  ->  {name}  ({w}x{h}, {bytes_written} bytes)")

def main():
    pngs = sorted(ASSETS.glob("*.png"))
    if not pngs:
        print("No PNGs in", ASSETS)
        sys.exit(1)
    print(f"Converting {len(pngs)} assets -> {OUT_C}")

    with open(OUT_C, "w") as c_out, open(OUT_H, "w") as h_out:
        c_out.write('// AUTO-GENERATED by tools/png_to_lvgl.py - do not edit.\n')
        c_out.write('#include <lvgl.h>\n\n')
        c_out.write('#ifndef LV_ATTRIBUTE_LARGE_CONST\n')
        c_out.write('#define LV_ATTRIBUTE_LARGE_CONST\n')
        c_out.write('#endif\n')

        h_out.write('// AUTO-GENERATED by tools/png_to_lvgl.py - do not edit.\n')
        h_out.write('#pragma once\n#include <lvgl.h>\n\n')

        for p in pngs:
            convert_one(p, c_out, h_out)

    print("Done.")

if __name__ == "__main__":
    main()
