// AUTO-GENERATED by tools/png_to_lvgl.py - do not edit.
#pragma once
#include <lvgl.h>

extern const lv_img_dsc_t bits_icon_big;
extern const lv_img_dsc_t bits_icon_small;
extern const lv_img_dsc_t bits_look_0;
extern const lv_img_dsc_t bits_look_1;
extern const lv_img_dsc_t bits_look_10;
extern const lv_img_dsc_t bits_look_11;
extern const lv_img_dsc_t bits_look_12;
extern const lv_img_dsc_t bits_look_13;
extern const lv_img_dsc_t bits_look_14;
extern const lv_img_dsc_t bits_look_2;
extern const lv_img_dsc_t bits_look_3;
extern const lv_img_dsc_t bits_look_4;
extern const lv_img_dsc_t bits_look_5;
extern const lv_img_dsc_t bits_look_6;
extern const lv_img_dsc_t bits_look_7;
extern const lv_img_dsc_t bits_look_8;
extern const lv_img_dsc_t bits_look_9;
